### ISSUE TITLE
The value 0 is not of type CHARACTER

### ISSUE THREAD

**Issue by shyguy** [rpav/fast-io#16]
I'm trying to write bytes to an instance of usocket, I create the socket first, then I create a buffer with the stream as an output then try to write to it then flush it to the stream, but I get the error: 'The value 0 is not of type CHARACTER' here is my code:

```lisp
(ql:quickload :usocket)
(ql:quickload :fast-io)
(setf *socket* (usocket:socket-listen "127.0.0.1" 25565))
(setf *client* (usocket:socket-accept *socket*))
(setf *output* (fast-io:make-output-buffer :output (usocket:socket-stream *client*)))
(fast-io:write32-be 100 *output*)
(fast-io:finish-output-buffer *output*)
```

Any ideas? Thanks.

**Comment by rpav** [comment]
Make sure the stream is `:element-type '(unsigned-byte 8)`.  I'm not sure how you set that with usocket.

**Comment by mhsjlw** [comment]
Got it, it's exactly how you wrote it, just add that to `socket-listen` and you're off. Thanks!

**Comment by shyguy** [comment]
Yup that does it, thanks!

**Comment by shyguy** [comment]
After running this code and using it on a client, it seems that the bytes aren't actually sent over the socket to the client... any ideas?

**Comment by rpav** [comment]
All fast-io does is `(write-sequence VECTOR STREAM ...)`; it doesn't `finish-output` on the stream itself (if that's necessary at all?).  I would try doing a `write-sequence` manually to a socket and see what you need to make that work.

(The rationale of not clearing the stream is because you may want control over when stuff *actually* gets flushed, writing multiple buffers, etc.  Assuming that's the issue.)

**Comment by shyguy** [comment]
Running a `(force-output (usocket:socket-stream *client*))` seemed to do the trick, thanks.
